DELETE http://localhost:3001/api/persons/2

###

DELETE https://obscure-hamlet-65476.herokuapp.com/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "", 
    "number": "404-123453"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Anna Honkanen",
    "number": "404-123453"
}
###
POST https://obscure-hamlet-65476.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Anna Honkanen",
    "number": "404-123453"
}
###

POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Anna", "number": ""
}
